# Generated by Django 5.1.1 on 2024-10-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('expenses', '0002_initial'),
        ('projects', '0003_remove_assignment_duration_assignment_assigned_date_and_more'),
        ('reports', '0002_alter_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.customuser'),
        ),
        migrations.AddField(
            model_name='report',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
